name: Update GitHub Stats

on:
  schedule:
    - cron: "0 0 * * *"  # Aktualizacja codziennie o północy UTC
  workflow_dispatch:  # Pozwala na ręczne uruchomienie workflow

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate GitHub Stats
        run: |
          curl -o github-stats.svg "https://github-readme-stats.vercel.app/api/top-langs/?username=${{ github.repository_owner }}&theme=aura&hide_border=true&layout=compact&count_private=true&token=${{ secrets.GH_STATS_PAT }}"

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add github-stats.svg
          git commit -m "Update GitHub Stats [Auto]"
          git push
